version: '3.8'
services:
  portfolio:
    image: sundaydied/sundays-internet-home:latest
    container_name: portfolio
    ports:
      - "8000:8000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
    read_only: true
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    pull_policy: always
    user: "portfoliouser"
    networks:
      - isolated_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    volumes:
      - ./cloudflared/credentials.json:/etc/cloudflared/credentials.json:ro
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml:ro
    command: tunnel --config /etc/cloudflared/config.yml run
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    cap_drop:
      - ALL
    read_only: true
    depends_on:
      - portfolio
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - isolated_network

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=60
    command: --cleanup portfolio cloudflared
    networks:
      - isolated_network

networks:
  isolated_network:
    driver: bridge
