import "./globals.css";
import Navbar from "@components/Navbar";
import Footer from "@components/Footer";
import { Box } from "@mui/material";

export const metadata = {
  title: "Create Next App by shivam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="main-content">
          
              <Navbar />
              <Box style={{ textAlign: "justify" }}>{children}</Box>
            
              <Footer />
            
        </div>
      </body>
    </html>
  );
}
