name: Verify Secrets

on:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        id: docker_login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          if [ $? -eq 0 ]; then
            echo "Docker Hub login successful!"
          else
            echo "Docker Hub login failed!" >&2
            exit 1
          fi
